### ISSUE TITLE
Use _.runInContext

### ISSUE THREAD

**Issue by jdalton** [raisch/lodash-sift#1]
Since you're using `mixin` in on the node package you should use [_.runInContext](https://lodash.com/docs#runInContext) to create a pristine instance of lodash to extend.

``` js
var _ = require('lodash').runInContext();
```

**Comment by raisch** [comment]
Good idea. Thanks.

**Comment by raisch** [comment]
done.

**Comment by jdalton** [comment]
:confetti_ball:
